# ai-generated: 100% - generated by Gemini CLI for specs
"""
pytest unit tests acting as the TDD test specification for the Service-Desk API.
All requirements (R-01 to R-25) and conflicts (C1 = wallclock, C2 = reopen, C3 = matrix) are covered.

These tests run against a running service desk instance configured via the SVCDESK_URL environment variable.
They use the standard library urllib.request to remain dependency-free and compatible with minimal Python 3.13 environments.
"""

import os
import json
import uuid
import pytest
import urllib.request
import urllib.error
from datetime import datetime, timedelta

# SVCDESK_URL defaults to http://localhost:8080 (R-01)
SVCDESK_URL = os.environ.get("SVCDESK_URL", "http://localhost:8080")


class SvcDeskClient:
    """
    An idiomatic, dependency-free HTTP client wrapper for the Service Desk API
    using Python's built-in urllib library.
    """
    def __init__(self, base_url: str):
        self.base_url = base_url.rstrip("/")

    def request(self, method: str, path: str, body: dict = None, test_clock: str = None) -> tuple[int, dict]:
        url = f"{self.base_url}{path}"
        headers = {"Content-Type": "application/json"}
        if test_clock:
            headers["X-Test-Clock"] = test_clock

        data = json.dumps(body).encode("utf-8") if body is not None else None
        req = urllib.request.Request(url, data=data, headers=headers, method=method)

        try:
            with urllib.request.urlopen(req) as resp:
                status = resp.status
                resp_content = resp.read().decode("utf-8")
                resp_body = json.loads(resp_content) if resp_content else {}
                return status, resp_body
        except urllib.error.HTTPError as e:
            status = e.code
            try:
                resp_content = e.read().decode("utf-8")
                resp_body = json.loads(resp_content) if resp_content else {}
            except Exception:
                resp_body = {"error": {"code": "http_error", "message": e.reason}}
            return status, resp_body
        except Exception as e:
            # Handle connection or other network-level errors
            return 500, {"error": {"code": "connection_error", "message": str(e)}}


@pytest.fixture
def client() -> SvcDeskClient:
    """Fixture providing a configured SvcDeskClient instance."""
    return SvcDeskClient(SVCDESK_URL)


# ==============================================================================
# 1. Health Endpoint Tests (R-02, API.md §1)
# ==============================================================================

def test_health_endpoint(client: SvcDeskClient):
    """
    R-02 / API.md §1: GET /health answers 200 with {"status": "ok", "service": "svcdesk"}.
    """
    status, body = client.request("GET", "/health")
    assert status == 200
    assert body.get("status") == "ok"
    assert body.get("service") == "svcdesk"


# ==============================================================================
# 2. Ticket Validation and Failure Tests (R-03, R-20, API.md §7)
# ==============================================================================

def test_ticket_creation_validation_failures(client: SvcDeskClient):
    """
    R-20 / API.md §7: Validation failures should yield 400 or 422 with a JSON body
    carrying an 'error' object.
    """
    # Base valid body to manipulate
    base_body = {
        "title": "Valid Ticket Title",
        "description": "Valid description",
        "reporter": {"name": "John Doe", "email": "john@example.com", "vip": False},
        "impact": 2,
        "urgency": 2
    }

    # Helper to check validation fails
    def assert_validation_error(modified_body):
        status, body = client.request("POST", "/tickets", body=modified_body, test_clock="2026-10-14T10:00:00Z")
        assert status in (400, 422), f"Expected 400/422 for body: {modified_body}, got {status}"
        assert "error" in body, f"Expected 'error' object in body: {body}"

    # Title validation
    # 1. Missing title
    body_missing_title = base_body.copy()
    body_missing_title.pop("title")
    assert_validation_error(body_missing_title)

    # 2. Empty title
    body_empty_title = base_body.copy()
    body_empty_title["title"] = ""
    assert_validation_error(body_empty_title)

    # 3. Title too long (201 characters, limit is 200)
    body_long_title = base_body.copy()
    body_long_title["title"] = "A" * 201
    assert_validation_error(body_long_title)

    # Reporter validation
    # 4. Missing reporter name
    body_missing_rep_name = base_body.copy()
    body_missing_rep_name["reporter"] = {"email": "john@example.com"}
    assert_validation_error(body_missing_rep_name)

    # 5. Missing reporter block
    body_missing_rep = base_body.copy()
    body_missing_rep.pop("reporter")
    assert_validation_error(body_missing_rep)

    # Impact validation (allowed: 1, 2, 3)
    # 6. Impact too high
    body_invalid_impact_high = base_body.copy()
    body_invalid_impact_high["impact"] = 4
    assert_validation_error(body_invalid_impact_high)

    # 7. Impact too low
    body_invalid_impact_low = base_body.copy()
    body_invalid_impact_low["impact"] = 0
    assert_validation_error(body_invalid_impact_low)

    # 8. Impact string instead of integer
    body_string_impact = base_body.copy()
    body_string_impact["impact"] = "high"
    assert_validation_error(body_string_impact)

    # Urgency validation (allowed: 1, 2, 3)
    # 9. Urgency too high
    body_invalid_urgency_high = base_body.copy()
    body_invalid_urgency_high["urgency"] = 4
    assert_validation_error(body_invalid_urgency_high)

    # 10. Urgency too low
    body_invalid_urgency_low = base_body.copy()
    body_invalid_urgency_low["urgency"] = 0
    assert_validation_error(body_invalid_urgency_low)

    # 11. Urgency string instead of integer
    body_string_urgency = base_body.copy()
    body_string_urgency["urgency"] = "cosmetic"
    assert_validation_error(body_string_urgency)

    # Description validation
    # 12. Description too long (> 4000 chars)
    body_long_desc = base_body.copy()
    body_long_desc["description"] = "D" * 4001
    assert_validation_error(body_long_desc)


def test_ticket_ignores_read_only_and_unknown_fields(client: SvcDeskClient):
    """
    R-20 / API.md §2, §7: Server-owned and unknown fields in the request
    are silently ignored, never rejected.
    """
    payload = {
        "title": "Printer Jammed",
        "reporter": {"name": "Anna Nowak", "email": "anna@example.com", "vip": False},
        "impact": 3,
        "urgency": 2,
        # Server-owned fields to be ignored
        "id": "11111111-2222-3333-4444-555555555555",
        "priority": "P1",
        "state": "closed",
        "created_at": "2026-10-14T10:00:00Z",
        "sla": {"ack_due_at": "2026-10-14T10:15:00Z", "resolve_due_at": "2026-10-14T14:00:00Z"},
        # Unknown fields to be ignored
        "custom_field": "some_value",
        "another_ignored": 42
    }

    status, body = client.request("POST", "/tickets", body=payload, test_clock="2026-10-14T10:00:00Z")
    assert status == 201
    assert body["state"] == "new"  # Ignored payload state, defaults to new
    assert body["priority"] == "P4"  # Ignored P1 payload, computed based on 3/2 matrix
    assert body["id"] != "11111111-2222-3333-4444-555555555555"  # Generated by server
    assert "custom_field" not in body  # Unknown fields ignored and omitted in response


# ==============================================================================
# 3. Priority and Conflict C3 (Matrix) Tests (R-04, R-05, R-06, Conflict C3, API.md §3)
# ==============================================================================

def test_priority_matrix_under_c3_matrix(client: SvcDeskClient):
    """
    R-04, R-05, Conflict C3: Under C3 = matrix, priority is derived exclusively
    from the impact/urgency matrix. The 'reporter.vip' flag is stored but
    completely ignored for priority calculations.
    """
    matrix_cases = [
        # (impact, urgency, expected_priority)
        (1, 1, "P1"), (1, 2, "P2"), (1, 3, "P3"),
        (2, 1, "P2"), (2, 2, "P3"), (2, 3, "P4"),
        (3, 1, "P3"), (3, 2, "P4"), (3, 3, "P4")
    ]

    for impact, urgency, expected_prio in matrix_cases:
        # Check standard non-VIP reporter
        payload = {
            "title": f"Matrix ticket {impact}/{urgency}",
            "reporter": {"name": "Test User", "vip": False},
            "impact": impact,
            "urgency": urgency
        }
        status, body = client.request("POST", "/tickets", body=payload, test_clock="2026-10-14T10:00:00Z")
        assert status == 201
        assert body["priority"] == expected_prio, f"Non-VIP {impact}/{urgency} expected {expected_prio}, got {body['priority']}"

        # Conflict C3: VIP flag is IGNORED in calculation
        # Even with VIP=True, priority must strictly match the expected matrix priority (e.g. 3/3 VIP is P4, NOT P2).
        payload_vip = {
            "title": f"Matrix ticket VIP {impact}/{urgency}",
            "reporter": {"name": "VIP User", "vip": True},
            "impact": impact,
            "urgency": urgency
        }
        status, body_vip = client.request("POST", "/tickets", body=payload_vip, test_clock="2026-10-14T10:00:00Z")
        assert status == 201
        assert body_vip["reporter"]["vip"] is True
        assert body_vip["priority"] == expected_prio, (
            f"C3 Error: VIP flag was NOT ignored. VIP {impact}/{urgency} expected {expected_prio}, got {body_vip['priority']}"
        )


# ==============================================================================
# 4. State Machine and Transitions (R-07, R-08, R-09, API.md §6)
# ==============================================================================

def test_happy_path_state_transitions(client: SvcDeskClient):
    """
    R-07, API.md §6: Verifies the legal lifecycle transitions:
    new -> acknowledged -> in_progress -> resolved -> closed
    Each action sets its respective event timestamp.
    """
    # Create new ticket
    payload = {
        "title": "State machine ticket",
        "reporter": {"name": "Agent Smith"},
        "impact": 2,
        "urgency": 2
    }
    status, ticket = client.request("POST", "/tickets", body=payload, test_clock="2026-10-14T10:00:00Z")
    assert status == 201
    assert ticket["state"] == "new"
    assert ticket["created_at"] == "2026-10-14T10:00:00Z"
    assert ticket["acknowledged_at"] is None
    assert ticket["resolved_at"] is None
    assert ticket["closed_at"] is None

    ticket_id = ticket["id"]

    # 1. Acknowledge: new -> acknowledged
    status, ticket = client.request("POST", f"/tickets/{ticket_id}/ack", test_clock="2026-10-14T10:05:00Z")
    assert status == 200
    assert ticket["state"] == "acknowledged"
    assert ticket["acknowledged_at"] == "2026-10-14T10:05:00Z"

    # 2. Start: acknowledged -> in_progress
    status, ticket = client.request("POST", f"/tickets/{ticket_id}/start", test_clock="2026-10-14T10:10:00Z")
    assert status == 200
    assert ticket["state"] == "in_progress"

    # 3. Resolve: in_progress -> resolved
    status, ticket = client.request("POST", f"/tickets/{ticket_id}/resolve", test_clock="2026-10-14T10:30:00Z")
    assert status == 200
    assert ticket["state"] == "resolved"
    assert ticket["resolved_at"] == "2026-10-14T10:30:00Z"

    # 4. Close: resolved -> closed
    status, ticket = client.request("POST", f"/tickets/{ticket_id}/close", test_clock="2026-10-14T10:45:00Z")
    assert status == 200
    assert ticket["state"] == "closed"
    assert ticket["closed_at"] == "2026-10-14T10:45:00Z"


def test_illegal_state_transitions_yield_409(client: SvcDeskClient):
    """
    R-08, API.md §6: Any illegal transitions return 409 Conflict.
    Closed tickets are immutable (R-09).
    """
    payload = {
        "title": "Strict State transitions",
        "reporter": {"name": "Agent Smith"},
        "impact": 2,
        "urgency": 2
    }
    status, ticket = client.request("POST", "/tickets", body=payload, test_clock="2026-10-14T10:00:00Z")
    assert status == 201
    ticket_id = ticket["id"]

    # Attempt to skip acknowledge (new -> start)
    status, body = client.request("POST", f"/tickets/{ticket_id}/start", test_clock="2026-10-14T10:05:00Z")
    assert status == 409
    assert "error" in body

    # Attempt to resolve from new
    status, body = client.request("POST", f"/tickets/{ticket_id}/resolve", test_clock="2026-10-14T10:05:00Z")
    assert status == 409

    # Attempt to close from new
    status, body = client.request("POST", f"/tickets/{ticket_id}/close", test_clock="2026-10-14T10:05:00Z")
    assert status == 409

    # Advance legal to acknowledged
    status, _ = client.request("POST", f"/tickets/{ticket_id}/ack", test_clock="2026-10-14T10:05:00Z")
    assert status == 200

    # Attempt to resolve from acknowledged
    status, body = client.request("POST", f"/tickets/{ticket_id}/resolve", test_clock="2026-10-14T10:10:00Z")
    assert status == 409

    # Advance to in_progress
    status, _ = client.request("POST", f"/tickets/{ticket_id}/start", test_clock="2026-10-14T10:10:00Z")
    assert status == 200

    # Attempt to close from in_progress
    status, body = client.request("POST", f"/tickets/{ticket_id}/close", test_clock="2026-10-14T10:15:00Z")
    assert status == 409

    # Advance to resolved
    status, _ = client.request("POST", f"/tickets/{ticket_id}/resolve", test_clock="2026-10-14T10:15:00Z")
    assert status == 200

    # Attempt to acknowledge or start from resolved
    status, body = client.request("POST", f"/tickets/{ticket_id}/ack", test_clock="2026-10-14T10:20:00Z")
    assert status == 409
    status, body = client.request("POST", f"/tickets/{ticket_id}/start", test_clock="2026-10-14T10:20:00Z")
    assert status == 409

    # Advance to closed
    status, _ = client.request("POST", f"/tickets/{ticket_id}/close", test_clock="2026-10-14T10:25:00Z")
    assert status == 200

    # Immutable closed ticket checks (R-09): Attempt any action other than reopen
    status, body = client.request("POST", f"/tickets/{ticket_id}/ack", test_clock="2026-10-14T10:30:00Z")
    assert status == 409
    status, body = client.request("POST", f"/tickets/{ticket_id}/start", test_clock="2026-10-14T10:30:00Z")
    assert status == 409
    status, body = client.request("POST", f"/tickets/{ticket_id}/resolve", test_clock="2026-10-14T10:30:00Z")
    assert status == 409
    status, body = client.request("POST", f"/tickets/{ticket_id}/close", test_clock="2026-10-14T10:30:00Z")
    assert status == 409


def test_action_on_unknown_id_yields_404(client: SvcDeskClient):
    """
    R-08, R-25: Action on a ticket that does not exist is a 404.
    """
    fake_id = str(uuid.uuid4())
    status, body = client.request("POST", f"/tickets/{fake_id}/ack")
    assert status == 404
    assert "error" in body


# ==============================================================================
# 5. Reopening and Conflict C2 (Reopen) Tests (R-10, R-11, Conflict C2, API.md §6)
# ==============================================================================

def test_reopen_window_under_c2_reopen(client: SvcDeskClient):
    """
    R-10, R-11, Conflict C2: Under C2 = reopen:
    - Reopen is allowed from 'resolved' and from 'closed' within 7 days.
    - Reopening returns the ticket to 'in_progress', and clears resolved_at and closed_at.
    - Outside the 7-day window, reopen is refused with 409 Conflict.
    """
    # Create ticket
    payload = {
        "title": "Reopen test ticket",
        "reporter": {"name": "Jane User"},
        "impact": 2,
        "urgency": 2
    }
    status, ticket = client.request("POST", "/tickets", body=payload, test_clock="2026-10-14T10:00:00Z")
    assert status == 201
    ticket_id = ticket["id"]

    # Transition to resolved at 2026-10-14T10:30:00Z
    client.request("POST", f"/tickets/{ticket_id}/ack", test_clock="2026-10-14T10:05:00Z")
    client.request("POST", f"/tickets/{ticket_id}/start", test_clock="2026-10-14T10:10:00Z")
    status, ticket = client.request("POST", f"/tickets/{ticket_id}/resolve", test_clock="2026-10-14T10:30:00Z")
    assert status == 200
    assert ticket["state"] == "resolved"
    assert ticket["resolved_at"] == "2026-10-14T10:30:00Z"

    # CASE A: Reopen from RESOLVED exactly 7 days later (2026-10-21T10:30:00Z) - should succeed
    status, ticket_reopened = client.request("POST", f"/tickets/{ticket_id}/reopen", test_clock="2026-10-21T10:30:00Z")
    assert status == 200, f"Expected reopen success, got {status}"
    assert ticket_reopened["state"] == "in_progress"
    assert ticket_reopened["resolved_at"] is None
    assert ticket_reopened["closed_at"] is None

    # Resolve again at 2026-10-21T11:00:00Z
    status, ticket = client.request("POST", f"/tickets/{ticket_id}/resolve", test_clock="2026-10-21T11:00:00Z")
    assert status == 200
    assert ticket["resolved_at"] == "2026-10-21T11:00:00Z"

    # CASE B: Reopen from RESOLVED 7 days + 1 second later (2026-10-28T11:00:01Z) - should fail
    status, error_body = client.request("POST", f"/tickets/{ticket_id}/reopen", test_clock="2026-10-28T11:00:01Z")
    assert status == 409
    assert "error" in error_body

    # Close ticket to test reopening from closed state
    status, ticket = client.request("POST", f"/tickets/{ticket_id}/close", test_clock="2026-10-28T11:15:00Z")
    assert status == 200
    assert ticket["state"] == "closed"
    assert ticket["closed_at"] == "2026-10-28T11:15:00Z"

    # CASE C: Under C2 = reopen, reopen is allowed from CLOSED. Reopen within 7 days from close (2026-11-04T11:15:00Z)
    status, ticket_reopened_closed = client.request("POST", f"/tickets/{ticket_id}/reopen", test_clock="2026-11-04T11:15:00Z")
    assert status == 200, f"C2 Error: expected reopening from closed to be allowed, got {status}"
    assert ticket_reopened_closed["state"] == "in_progress"
    assert ticket_reopened_closed["resolved_at"] is None
    assert ticket_reopened_closed["closed_at"] is None

    # Close again at 2026-11-04T12:00:00Z (Must resolve -> close)
    client.request("POST", f"/tickets/{ticket_id}/resolve", test_clock="2026-11-04T11:30:00Z")
    client.request("POST", f"/tickets/{ticket_id}/close", test_clock="2026-11-04T12:00:00Z")

    # CASE D: Reopen from CLOSED 7 days + 1 second later (2026-11-11T12:00:01Z) - should fail
    status, error_body = client.request("POST", f"/tickets/{ticket_id}/reopen", test_clock="2026-11-11T12:00:01Z")
    assert status == 409
    assert "error" in error_body


# ==============================================================================
# 6. SLA Vector and Clock Calculations (C1 = wallclock, API.md §4)
# ==============================================================================

@pytest.mark.parametrize("vector_id, priority, created_at, expected_ack, expected_resolve", [
    # T1: P1, created Wednesday 12:00 CEST. P1 is wall-clock under C1 = wallclock.
    ("T1", "P1", "2026-10-14T10:00:00Z", "2026-10-14T10:15:00Z", "2026-10-14T14:00:00Z"),
    # T2: P3, created Friday 15:30 CEST. P3 is always business-hours.
    ("T2", "P3", "2026-10-16T13:30:00Z", "2026-10-19T09:30:00Z", "2026-10-21T13:30:00Z"),
    # T3: P1, created Friday 17:00 CEST. P1 is wall-clock.
    ("T3", "P1", "2026-10-16T15:00:00Z", "2026-10-16T15:15:00Z", "2026-10-16T19:00:00Z"),
    # T4: P2, created Saturday 12:00 CEST. P2 is always business-hours. (Monday 16:00 local = 14:00Z)
    ("T4", "P2", "2026-10-17T10:00:00Z", "2026-10-19T07:00:00Z", "2026-10-19T14:00:00Z"),
    # T5: P4, created Thursday 15:30 CET (Jan). P4 is always business-hours. (Wednesday 15:30 local = 14:30Z)
    ("T5", "P4", "2027-01-14T14:30:00Z", "2027-01-15T14:30:00Z", "2027-01-27T14:30:00Z"),
    # T6: P1, created Friday 16:50 CET. P1 is wall-clock.
    ("T6", "P1", "2027-01-15T15:50:00Z", "2027-01-15T16:05:00Z", "2027-01-15T19:50:00Z"),
    # T7: P2, created Wednesday 12:00 CEST. P2 is always business-hours. (Thursday 12:00 local = 10:00Z)
    ("T7", "P2", "2026-10-14T10:00:00Z", "2026-10-14T11:00:00Z", "2026-10-15T10:00:00Z"),
    # T8: P3, created Friday 15:00 CEST (DST ends Sun). P3 is always business-hours. (Wednesday 15:00 CET = 14:00Z)
    ("T8", "P3", "2026-10-23T13:00:00Z", "2026-10-26T10:00:00Z", "2026-10-28T14:00:00Z")
])
def test_sla_vectors_under_c1_wallclock(client: SvcDeskClient, vector_id, priority, created_at, expected_ack, expected_resolve):
    """
    R-12, R-13, R-14, Conflict C1: Under C1 = wallclock:
    - P1 SLA targets are wall-clock (24/7).
    - P2, P3, P4 SLA targets count only business hours (Mon-Fri 08:00-16:00 Europe/Warsaw).
    Verifies that the API returns the exact SLA due dates corresponding to the T1..T8 test vectors.
    """
    # Map priority to impact/urgency to produce that priority under matrix
    # P1 -> 1, 1
    # P2 -> 2, 1
    # P3 -> 1, 3
    # P4 -> 2, 3
    prio_map = {
        "P1": (1, 1),
        "P2": (2, 1),
        "P3": (1, 3),
        "P4": (2, 3)
    }
    impact, urgency = prio_map[priority]

    payload = {
        "title": f"SLA Vector {vector_id}",
        "reporter": {"name": "Test Runner"},
        "impact": impact,
        "urgency": urgency
    }

    status, body = client.request("POST", "/tickets", body=payload, test_clock=created_at)
    assert status == 201, f"Failed to create ticket for vector {vector_id}"
    assert body["priority"] == priority

    # Verify both due instants inside the created ticket's SLA block match the vector
    sla = body.get("sla", {})
    assert sla.get("ack_due_at") == expected_ack, f"{vector_id}: ack_due_at mismatch. Expected {expected_ack}, got {sla.get('ack_due_at')}"
    assert sla.get("resolve_due_at") == expected_resolve, f"{vector_id}: resolve_due_at mismatch. Expected {expected_resolve}, got {sla.get('resolve_due_at')}"


# ==============================================================================
# 7. SLA Status, Breach, and Pause (R-15, R-16, API.md §5)
# ==============================================================================

def test_sla_breach_and_pause_behavior(client: SvcDeskClient):
    """
    R-15, R-16, API.md §5: Verifies that GET /tickets/{id}/sla returns the correct:
    - ack_breached: true if now > ack_due_at and not ack'd, or ack'd > ack_due_at
    - resolve_breached: true if now > resolve_due_at and not resolved, or resolved > resolve_due_at
    - paused: true if not resolved/closed, business-clock target, and now is outside business hours
    """
    # Create T4 (P2) ticket (business clock): Saturday 2026-10-17T10:00:00Z
    # ack_due_at = 2026-10-19T07:00:00Z
    # resolve_due_at = 2026-10-19T14:00:00Z
    payload = {
        "title": "Breach & Pause check",
        "reporter": {"name": "SLA Inspector"},
        "impact": 2,
        "urgency": 1
    }
    status, ticket = client.request("POST", "/tickets", body=payload, test_clock="2026-10-17T10:00:00Z")
    assert status == 201
    assert ticket["priority"] == "P2"
    ticket_id = ticket["id"]

    # --- Case 1: Check SLA on Saturday 12:00Z (outside business hours, not acknowledged)
    status, sla = client.request("GET", f"/tickets/{ticket_id}/sla", test_clock="2026-10-17T12:00:00Z")
    assert status == 200
    assert sla["ack_breached"] is False
    assert sla["resolve_breached"] is False
    assert sla["paused"] is True  # Active, business-hours ticket checked outside business hours

    # --- Case 2: Check SLA exactly at the due instant: Monday 2026-10-19T07:00:00Z (No breach yet)
    status, sla = client.request("GET", f"/tickets/{ticket_id}/sla", test_clock="2026-10-19T07:00:00Z")
    assert status == 200
    assert sla["ack_breached"] is False
    assert sla["paused"] is False  # Monday 09:00 CEST is inside business hours

    # --- Case 3: Check SLA after due instant: Monday 2026-10-19T07:00:01Z (Breach occurs)
    status, sla = client.request("GET", f"/tickets/{ticket_id}/sla", test_clock="2026-10-19T07:00:01Z")
    assert status == 200
    assert sla["ack_breached"] is True

    # --- Case 4: Acknowledge late (at 2026-10-19T07:05:00Z) and verify breach persists
    client.request("POST", f"/tickets/{ticket_id}/ack", test_clock="2026-10-19T07:05:00Z")
    status, sla = client.request("GET", f"/tickets/{ticket_id}/sla", test_clock="2026-10-19T08:00:00Z")
    assert status == 200
    assert sla["ack_breached"] is True  # Late acknowledgement = permanently breached

    # --- Case 5: Verify wall-clock tickets (P1) are NEVER paused under C1 = wallclock
    # Create T1 (P1) ticket at Wednesday 2026-10-14T10:00:00Z
    payload_p1 = {
        "title": "P1 Wallclock pause check",
        "reporter": {"name": "SLA Inspector"},
        "impact": 1,
        "urgency": 1
    }
    status, ticket_p1 = client.request("POST", "/tickets", body=payload_p1, test_clock="2026-10-14T10:00:00Z")
    assert status == 201
    assert ticket_p1["priority"] == "P1"
    ticket_p1_id = ticket_p1["id"]

    # Check SLA at Wednesday 18:00Z (20:00 CEST, outside business hours)
    status, sla_p1 = client.request("GET", f"/tickets/{ticket_p1_id}/sla", test_clock="2026-10-14T18:00:00Z")
    assert status == 200
    assert sla_p1["paused"] is False  # P1 uses wallclock, so it is never paused


# ==============================================================================
# 8. Listing and Filtering Tests (R-19, API.md §1)
# ==============================================================================

def test_ticket_listing_and_filtering(client: SvcDeskClient):
    """
    R-19, API.md §1: GET /tickets lists all tickets.
    Supports optional exact-match filters for 'state' and 'priority'.
    """
    # 1. Clear state or work with current tickets. Let's create two unique tickets with specific states and priorities
    p1_title = f"Filter P1 - {uuid.uuid4()}"
    p3_title = f"Filter P3 - {uuid.uuid4()}"

    # Create first ticket (P1, state starts as 'new')
    status, t1 = client.request("POST", "/tickets", body={
        "title": p1_title,
        "reporter": {"name": "Filter tester"},
        "impact": 1,
        "urgency": 1
    }, test_clock="2026-10-14T10:00:00Z")
    assert status == 201
    t1_id = t1["id"]

    # Create second ticket (P3, transition to 'acknowledged')
    status, t2 = client.request("POST", "/tickets", body={
        "title": p3_title,
        "reporter": {"name": "Filter tester"},
        "impact": 1,
        "urgency": 3
    }, test_clock="2026-10-14T10:00:00Z")
    assert status == 201
    t2_id = t2["id"]

    # Transition second ticket to 'acknowledged'
    client.request("POST", f"/tickets/{t2_id}/ack", test_clock="2026-10-14T10:05:00Z")

    # Fetch full list and verify both are returned
    status, all_tickets = client.request("GET", "/tickets")
    assert status == 200
    assert isinstance(all_tickets, list)
    titles = [t["title"] for t in all_tickets]
    assert p1_title in titles
    assert p3_title in titles

    # Filter by state: state=acknowledged
    status, ack_tickets = client.request("GET", "/tickets?state=acknowledged")
    assert status == 200
    for t in ack_tickets:
        assert t["state"] == "acknowledged"
    ack_titles = [t["title"] for t in ack_tickets]
    assert p3_title in ack_titles
    assert p1_title not in ack_titles

    # Filter by priority: priority=P1
    status, p1_tickets = client.request("GET", "/tickets?priority=P1")
    assert status == 200
    for t in p1_tickets:
        assert t["priority"] == "P1"
    p1_titles = [t["title"] for t in p1_tickets]
    assert p1_title in p1_titles
    assert p3_title not in p1_titles

    # Filter by both state and priority: state=new&priority=P1
    status, combined_tickets = client.request("GET", "/tickets?state=new&priority=P1")
    assert status == 200
    for t in combined_tickets:
        assert t["state"] == "new"
        assert t["priority"] == "P1"
    combined_titles = [t["title"] for t in combined_tickets]
    assert p1_title in combined_titles
    assert p3_title not in combined_titles
