from fastapi import FastAPI, Request, HTTPException, status
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field
from datetime import datetime, timedelta, timezone, time
from typing import Optional, Dict, Any
import uuid
from zoneinfo import ZoneInfo
# ai-generated: 100% - generated by AI for source code
app = FastAPI()

# Timezone
WARSAW_TZ = ZoneInfo("Europe/Warsaw")

# In-memory storage
tickets_db: Dict[str, Any] = {}

# Exception Handler - The Global Requirement
async def error_response(status_code: int, code: str, message: str):
    return JSONResponse(
        status_code=status_code,
        content={"error": {"code": code, "message": message}}
    )

@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request: Request, exc: RequestValidationError):
    # Flatten error messages for clarity
    messages = [f"{e['loc']}: {e['msg']}" for e in exc.errors()]
    return await error_response(422, "validation_error", "; ".join(messages))

@app.exception_handler(HTTPException)
async def http_exception_handler(request: Request, exc: HTTPException):
    # Ensure error format
    if isinstance(exc.detail, dict) and "error" in exc.detail:
        return JSONResponse(status_code=exc.status_code, content=exc.detail)
    return await error_response(exc.status_code, "error", str(exc.detail))

# Exception handler for general errors
@app.exception_handler(Exception)
async def general_exception_handler(request: Request, exc: Exception):
    return await error_response(500, "internal_error", "An unexpected error occurred.")

# Helpers
def format_iso(dt: datetime) -> str:
    # Ensure it's UTC and formatted with Z
    return dt.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

def get_now(request: Request) -> datetime:
    """Gets current time, or from X-Test-Clock header if present."""
    clock_header = request.headers.get("X-Test-Clock")
    if not clock_header:
        return datetime.now(timezone.utc)
    
    try:
        # Assuming format YYYY-MM-DDTHH:MM:SSZ
        return datetime.fromisoformat(clock_header.replace("Z", "+00:00"))
    except ValueError:
        # Need to raise an exception that the handler catches and formats
        raise HTTPException(status_code=400, detail={"error": {"code": "invalid_date", "message": "Invalid X-Test-Clock format"}})

# Models
class Reporter(BaseModel):
    name: str
    email: Optional[str] = None
    vip: bool = False

class TicketBase(BaseModel):
    title: str = Field(..., min_length=1, max_length=200)
    description: Optional[str] = Field(None, max_length=4000)
    reporter: Reporter
    impact: int = Field(..., ge=1, le=3)
    urgency: int = Field(..., ge=1, le=3)

# SLA Business Hours Logic
def add_business_time(start_dt_utc: datetime, hours: float) -> datetime:
    # 1. Convert to Warsaw.
    dt = start_dt_utc.astimezone(WARSAW_TZ)
    
    # Helper to move to start of next business day
    def get_next_business_day_start(d: datetime) -> datetime:
        d += timedelta(days=1)
        while d.weekday() >= 5:
            d += timedelta(days=1)
        return d.replace(hour=8, minute=0, second=0, microsecond=0, tzinfo=WARSAW_TZ)

    # 2. Weekend or >= 16:00 -> 08:00 next business day
    if dt.weekday() >= 5 or dt.time() >= time(16, 0, 0):
        dt = get_next_business_day_start(dt.replace(hour=16, minute=0, second=0, microsecond=0, tzinfo=WARSAW_TZ))
    # 3. < 08:00 -> 08:00 same day
    elif dt.time() < time(8, 0, 0):
        dt = dt.replace(hour=8, minute=0, second=0, microsecond=0, tzinfo=WARSAW_TZ)
        
    # 4. Loop
    remaining_hours = hours
    while remaining_hours > 0:
        # a) Calc hours to end
        end_of_day = dt.replace(hour=16, minute=0, second=0, microsecond=0, tzinfo=WARSAW_TZ)
        hours_to_end = (end_of_day - dt).total_seconds() / 3600
        
        # b) remaining <= to_end
        if remaining_hours <= hours_to_end:
            dt += timedelta(hours=remaining_hours)
            remaining_hours = 0
        # c) remaining > to_end
        else:
            remaining_hours -= hours_to_end
            dt = get_next_business_day_start(dt)
            
    return dt.astimezone(timezone.utc)

def calculate_sla(priority: str, created_at: datetime):
    # SLA Hours
    # P1: Ack 15m, Resolve 4h (Not strictly business hours? P1 is usually 24/7. Assuming P1 is 24/7)
    # The requirement says "Pause logic: business clock (P2,P3,P4)". 
    # This implies P1 is not business clock.
    
    if priority == "P1":
        return {
            "ack_due_at": format_iso(created_at + timedelta(minutes=15)),
            "resolve_due_at": format_iso(created_at + timedelta(hours=4))
        }
    
    sla_map = {
        "P2": {"ack": 1, "res": 8},
        "P3": {"ack": 4, "res": 24},
        "P4": {"ack": 8, "res": 72},
    }
    
    ack_hours = sla_map[priority]["ack"]
    res_hours = sla_map[priority]["res"]
    
    return {
        "ack_due_at": format_iso(add_business_time(created_at, ack_hours)),
        "resolve_due_at": format_iso(add_business_time(created_at, res_hours))
    }

# Endpoints
@app.post("/tickets", status_code=201)
async def create_ticket(ticket_in: TicketBase, request: Request):
    now = get_now(request)
    
    # Priority Matrix
    priority_matrix = {
        (1, 1): "P1", (1, 2): "P2", (1, 3): "P3",
        (2, 1): "P2", (2, 2): "P3", (2, 3): "P4",
        (3, 1): "P3", (3, 2): "P4", (3, 3): "P4"
    }
    priority = priority_matrix[(ticket_in.impact, ticket_in.urgency)]
    
    ticket_id = str(uuid.uuid4())
    ticket = {
        "id": ticket_id,
        "title": ticket_in.title,
        "description": ticket_in.description,
        "reporter": ticket_in.reporter.model_dump(),
        "impact": ticket_in.impact,
        "urgency": ticket_in.urgency,
        "priority": priority,
        "state": "new",
        "created_at": format_iso(now),
        "acknowledged_at": None,
        "resolved_at": None,
        "closed_at": None,
        "sla": {"ack_due_at": None, "resolve_due_at": None}
    }
    
    # SLA Calculations
    ticket["sla"] = calculate_sla(priority, now)
    
    tickets_db[ticket_id] = ticket
    return ticket

@app.get("/tickets")
async def list_tickets(state: Optional[str] = None, priority: Optional[str] = None):
    results = list(tickets_db.values())
    if state:
        results = [t for t in results if t["state"] == state]
    if priority:
        results = [t for t in results if t["priority"] == priority]
    return results

@app.get("/tickets/{ticket_id}")
async def get_ticket(ticket_id: str):
    if ticket_id not in tickets_db:
        raise HTTPException(status_code=404, detail={"error": {"code": "not_found", "message": "Ticket not found"}})
    return tickets_db[ticket_id]

@app.post("/tickets/{ticket_id}/{action}")
async def transition_ticket(ticket_id: str, action: str, request: Request):
    if ticket_id not in tickets_db:
        raise HTTPException(status_code=404, detail={"error": {"code": "not_found", "message": "Ticket not found"}})
    
    ticket = tickets_db[ticket_id]
    now = get_now(request)
    
    if action == "ack" and ticket["state"] == "new":
        ticket["state"] = "acknowledged"
        ticket["acknowledged_at"] = format_iso(now)
    elif action == "start" and ticket["state"] == "acknowledged":
        ticket["state"] = "in_progress"
    elif action == "resolve" and ticket["state"] == "in_progress":
        ticket["state"] = "resolved"
        ticket["resolved_at"] = format_iso(now)
    elif action == "close" and ticket["state"] == "resolved":
        ticket["state"] = "closed"
        ticket["closed_at"] = format_iso(now)
    elif action == "reopen" and ticket["state"] in ["resolved", "closed"]:
        check_time = datetime.fromisoformat(ticket["resolved_at"].replace("Z", "+00:00")) if ticket["resolved_at"] else datetime.fromisoformat(ticket["closed_at"].replace("Z", "+00:00"))
        if (now - check_time).days < 7:
            ticket["state"] = "in_progress"
            ticket["resolved_at"] = None
            ticket["closed_at"] = None
        else:
            raise HTTPException(status_code=409, detail={"error": {"code": "reopen_expired", "message": "Reopen window expired"}})
    else:
        raise HTTPException(status_code=409, detail={"error": {"code": "illegal_transition", "message": "Illegal state transition"}})
    
    tickets_db[ticket_id] = ticket
    return ticket

@app.get("/tickets/{ticket_id}/sla")
async def get_ticket_sla(ticket_id: str, request: Request):
    if ticket_id not in tickets_db:
        raise HTTPException(status_code=404, detail={"error": {"code": "not_found", "message": "Ticket not found"}})
    
    ticket = tickets_db[ticket_id]
    now = get_now(request)
    
    ack_due = datetime.fromisoformat(ticket["sla"]["ack_due_at"].replace("Z", "+00:00"))
    res_due = datetime.fromisoformat(ticket["sla"]["resolve_due_at"].replace("Z", "+00:00"))
    
    ack_breached = (now > ack_due) and (ticket["acknowledged_at"] is None or datetime.fromisoformat(ticket["acknowledged_at"].replace("Z", "+00:00")) > ack_due)
    resolve_breached = (now > res_due) and (ticket["resolved_at"] is None or datetime.fromisoformat(ticket["resolved_at"].replace("Z", "+00:00")) > res_due)
    
    paused = False
    if ticket["priority"] != "P1" and ticket["state"] not in ["resolved", "closed"]:
        now_warsaw = now.astimezone(WARSAW_TZ)
        if now_warsaw.weekday() >= 5 or not (8 <= now_warsaw.hour < 16):
            paused = True
            
    return {
        "ack_breached": ack_breached,
        "resolve_breached": resolve_breached,
        "paused": paused
    }

@app.get("/health")
async def health():
    return {"status": "ok", "service": "svcdesk"}
